### ISSUE TITLE
Needs more examples

### ISSUE THREAD

**Issue by veox** [veox/python3-krakenex#10]
Has been brought up on Twitter. Requester failed to follow up with examples of what needs examples.

If you think something would make a good example, drop a comment (or PR).

**Comment by bhaktatejas922** [comment]
An example using the printing the result of an API call would be great. Say OHLC data for example, and printing the array.

**Comment by bhaktatejas922** [comment]
Using the result of an API call is a bit weird to understand from the documentation on krakens site

**Comment by veox** [comment]
Example: full logging.

Seeing how Kraken only keeps a short history available directly, including in its integration with cryptowat.ch, - show how to get the ledger while it's still available, and store locally.

Bonus points for instructions on displaying this historic data, e.g. by converting to a dataset understood by a web widget.

**Comment by Dessoul** [comment]
Hi,

I have made a simple script that send a market order.
The pair, type and volume can be set with a configuration file.
I personally use this to make a Dollars cost averaging strategy, just as described here : https://www.reddit.com/r/CryptoCurrency/comments/5yyqn6/help_dollarcost_averaging_buying_eth_btc_on_a/

If you think it can be useful, I can upload this with pleasure on example section.

**Comment by veox** [comment]
Sounds OK to me @Dessoul - just make sure _not_ to include API keys in `git` history. :)

**Comment by Dessoul** [comment]
@veox it is done. As I am not really comfortable with collaborative use of GitHub I hope I did not make a mess on the repo.
Feel free to tell me if there is any problem.
By the way, thanks for the job. Your library is just perfect !

**Comment by veox** [comment]
Cool. For ref, that'd be PR #14.

Closing this issue, since there's enough examples now IMO, considering the how tiny `krakenex` itself is.

**Comment by AlexFine** [comment]
@veox thanks for putting this all together. Maybe this is a dumb question, but in "AddOrder," how do you short with margin trading? Do you just sell with leverage?

**Comment by veox** [comment]
@AlexFine I have no clue; I've never used the package for margin trading.

In a few "manual" attempts through Kraken's web interfaces, that indeed seemed the way: sell with leverage. But don't trust me on this one.

**Comment by AlexFine** [comment]
@veox I'll spend some more time investigating it independently. Once I get it working I'd be happy to make an example and push it to this repo if you're interested in adding it in the examples folder. If not no worries.
