### ISSUE TITLE
Inconsistent behavior, some API methods returning {'error': ['EAPI:Invalid key']} from API

### ISSUE THREAD

**Issue by 15chrjef** [veox/python3-krakenex#104]
### Versions

```
OS:       Mac Mojave
Python:   3.6
krakenex: Latest
```

### What are you trying to achieve?
using the query orders function from the kraken api

``` python
# code sample *trade variable defined properly above*
import krakenex
self.client = krakenex.API(config['public_api_key'], config['private_api_key'])
trades = self.client.query_private(TRADES_HISTORY)[RESULT][TRADES]
order_info = self.client.query_private(QUERY_ORDERS, {'oflags': 'viqc', 'txid': [trade['orderId']]})
print('trades', trades)
print('order_info', order_info)

```

### What do you expect to happen?
For the first api call to return the trade history on the account.
For the second api call to return the relevant information for the requested order.

### What happens instead?
The first api call returns the requested trades normally.
The second api call returns an error 
```
{'error': ['EAPI:Invalid key']}
```

``` python
# error message

```

**Comment by veox** [comment]
You have a mix-up in API method names and arguments for them.

Since you don't show what `QUERY_ORDERS` is, I'll just point you to [the docs](https://www.kraken.com/help/api#query-orders-info).

**Comment by veox** [comment]
If I understand correctly, you'll want to drop the `oflags`.

**Comment by 15chrjef** [comment]
Thanks for the response!
1) I believe the API method names is correct. Straight from the docs "Query orders info
URL: https://api.kraken.com/0/private/QueryOrders"

The QUERY_ORDERS is an internal variable that resolves to 'QueryOrders' which is correct to my knowledge.

2) Dropping the ```oflags``` so the code is 
```order_info = self.client.query_private(QUERY_ORDERS, {'oflags': 'viqc', 'txid': [trade['orderId']]})```
produces the same result as before

**Comment by veox** [comment]
> Dropping the `oflags` so the code is (...)

The `oflags` is still present in the line you quote. Did you or did you not drop it?..

As you may see from the docs, `'QueryOrders'` Does not have an `oflags` parameter - which why I suggested dropping it. However - just checked - adding/removing the parameter has no effect - the response always has `'oflags': 'fciq'` set. In other words, this is not your issue.

-----

The error is therefore likely in your `self.client` implementation. I am not clairvoyant, but you are likely overriding the session, resetting the key, or doing something of the sort.

> Any ideas on how to solve this issue?

Simplify your example into a copy-pastable script.

**Comment by veox** [comment]
Reopen if you can demonstrate that the issue is with `krakenex`.

**Comment by 15chrjef** [comment]
I have isolated and reproduced the problem with 6 lines of code. I am fairly certain this is specific to krakenex.

```
import krakenex
client = krakenex.API('OYX...', 'QWR...')
trades = client.query_private('TradesHistory')['result']['trades']
order_info = client.query_private('QueryOrders', {'trades': 'true', 'txid': ['O..']})
print('orderinfo', order_info2)
print('trades', trades)
```
I am getting the same behavior as before where the variable ```trades``` is defined and returning correctly, however the ```order_info``` from QueryOrders is still returning ```{'error': ['EAPI:Invalid key']}```.

There is no possibility of the client getting reset, or overriding the session in this case. It appears to be an issue with Krakenex or that Kraken has changed what it returns. The most likely scenarios that I can think of are as followed.

1) Krakenex is returning the incorrect error message for my request
2) Kraken is returning the incorrect error message for my request
3) Krakenex is returning an error message that is a catch all for unknown errors

**Comment by veox** [comment]
You are still not copying the actual code that you're using. :/

This works perfectly fine for me:

``` python
#!/usr/bin/env python
# https://github.com/veox/python3-krakenex/issues/104#issuecomment-444894546

import krakenex

client = krakenex.API('foo...', 'bar...')

trades = client.query_private('TradesHistory')['result']['trades']
print('trades', trades)

print('-'*72)

order_info = client.query_private('QueryOrders', {'trades': 'true', 'txid': 'O...'})
print('orderinfo', order_info)
```

So, this is not specific to `krakenex`.

It could be something about Mac, or the `krakenex` version you're using, although both are unlikely. (BTW, `Latest` is not helpful. If it's `git master`, then specify a commit with `git describe --always`, because `master` _could_ have drifted. If it's a stable installed through `pip`, then specify through `pip freeze | grep krakenex`.)

But more probably, since we've eliminated it being something in your code, it's your key not having permissions for the action. For example, you could've disallowed querying closed orders, or something like that.

**Comment by philippose** [comment]
Hi,
The first thought that went through my mind when I saw this issue is that maybe the API key does not have the required permissions. 

I would suggest that you first verify on the Kraken website whether you have supplied your API key with the right permissions. 

Regards, 
Philippose

**Comment by veox** [comment]
Closing as stale.
