### ISSUE TITLE
Simplified krakenex: not working

### ISSUE THREAD

**Issue by ecofrugalism** [veox/python3-krakenex#106]
I tried to use krakenex, by just using these files (not the entire krakenex):
kraken.key
version.py
api.py

Api.py was altered a bit by changing line 31 so that it reads:
import version

Then, in terminal, I typed: 
python3 -c "import api;k=api.API();k.load_key('kraken.key');print(k.query_private('Balance'))"

Problem is that says:
{'error': ['EAPI:Invalid signature']}

I'm on gentoo, using python 3.5.5

**Comment by veox** [comment]
Use the package as provided. Installation instructions are in the `README`.
