### ISSUE TITLE
Add feature: add standard order (buy or sell)

### ISSUE THREAD

**Issue by generalcodingprojects** [veox/python3-krakenex#109]
Can you add an entry in /krakenex/api.py to allow for making standard orders (buy or sell; market and/or limit orders) ? Can you also add an example in /examples for making such a standard sell or buy order ?

**Comment by veox** [comment]
> Can you add an entry in /krakenex/api.py to allow for making standard orders (buy or sell; market and/or limit orders) ?

No. From `README`:

> Intended for developers, not traders.

You can take a look at [`pykrakenapi`](https://github.com/dominiktraxl/pykrakenapi) which uses `krakenex` as a dependency.

(Duplicatge of issue #40.)

-----

> Can you also add an example in /examples for making such a standard sell or buy order ?

Use the slightly more complex [`order-conditional-close.py`](https://github.com/veox/python3-krakenex/blob/master/examples/order-conditional-close.py) and remove the parameters you don't want.

**Comment by veox** [comment]
Closing as duplicate.
