### ISSUE TITLE
Can't cancel order

### ISSUE THREAD

**Issue by TOTANICS** [veox/python3-krakenex#110]
### Versions

```
OS:      Linux
Python:   3.6.7
krakenex: latest
```

### What are you trying to achieve?
Having placed an order "AddOrder", I attempt to cancel it, but this fails and returns an error.

``` python
adding the order...
`def add_sell_order()
		res = api.query_private('AddOrder',{
			'pair': 'BCHEUR',
			'type': 'sell',
			'ordertype': 'limit',
			'price': myprice,
			'volume': myvolume})
		print(res)
`
This gets me among other things the 'txid' which we'll call 'mytxid'

If I then pass this to my cancel order function...

`def cancel_sell_order()
		res = api.query_private('CancelOrder',{
			'txid': mytxid})
		print(res)
`
I get the following output:

{'error': ['EOrder:Invalid order']}



```

### What do you expect to happen?

As above I expect the order to cancel

### What happens instead?

As above described

``` python
# error message
see above
```
If I search for open orders that order is still there waiting to fill or be canceled but I can't cancel it through the API.
Any ideas? Thanks!

**Comment by veox** [comment]
What happened? Did you close by accident, or figure it out?

If the latter, please do give a brief description, in case someone stumbles on the same issue.

**Comment by adm-github** [comment]
Issue is still unsolved

**Comment by veox** [comment]
@adm-github Then open a new issue with something more reproducible than this.
