### ISSUE TITLE
Doing ticker request with multiple pairs

### ISSUE THREAD

**Issue by generalcodingprojects** [veox/python3-krakenex#111]
I tried doing a ticker request with multiple pairs:
python3 -c "import api;k=api.API();print(k.query_public('Ticker',{'pair': 'XXRPZEUR' 'XREPZEUR' 'ADAEUR' 'DASHEUR' 'EOSEUR' 'GNOEUR' 'QTUMEUR' 'XLTCZEUR' 'XXLMZEUR' 'XXMRZEUR' 'XTZEUR' 'XZECZEUR'}))")

This doesn't seem to work; it gives an error: [ 'Equery:Unkown asset pair' ]

If I try doing just one, ie 'XREPZEUR' then that works, but it doesn't work when doing the request with multiple pairs. What am I doing wrong and how can I make it work ?
I can't do each request separately since that would increase the callratecounter too much.

**Comment by veox** [comment]
https://www.kraken.com/help/api#get-ticker-info
