### ISSUE TITLE
GetWebSocketsToken

### ISSUE THREAD

**Issue by kkagill** [veox/python3-krakenex#120]
### Versions

```
OS: Windows 10
Python: 3.6.8
krakenex: 
```

### What are you trying to achieve?

Hi, I'm trying to get a token for websocket.

**Authentication
The API client must request an authentication "token" via the following REST API endpoint "GetWebSocketsToken" to connect to WebSockets Private endpoints. The token should be used within 15 minutes of creation. The token does not expire once a connection to a WebSockets API private message (openOrders or ownTrades) is maintained.**

Endpoint URL: https://api.kraken.com/0/private/GetWebSocketsToken

Do you guys have any example to get a token with this API? or any code snippets would be apprecaited.

**Comment by veox** [comment]
If you've found the answer yourself, consider posting it here for others to find.

**Comment by kkagill** [comment]
To get token, it's this
```
k = krakenex.API()
k.load_key('kraken.key')
data = k.query_private('GetWebSocketsToken')
self.token = data['result']['token']
```
