### ISSUE TITLE
Can't expire a websocket token received through GetWebSocketsToken

### ISSUE THREAD

**Issue by Turegano** [veox/python3-krakenex#127]
### What are you trying to achieve?

Expire WS_Token

### What do you expect to happen?
Invalidate token

### What happens instead?

The token is valid everlasting

**Comment by veox** [comment]
Why do you think it can be manually expired? From [Kraken's docs](https://www.kraken.com/features/api#ws-auth):

> The API client must request an authentication "token" via the following REST API endpoint "GetWebSocketsToken" to connect to WebSockets Private endpoints. The token should be used within 15 minutes of creation. **The token does not expire once a connection to a WebSockets API private message (openOrders or ownTrades) is maintained.**

Without additional info, this issue is unactionable.

**Comment by veox** [comment]
Closed as stale.
