### ISSUE TITLE
Add Order Broken

### ISSUE THREAD

**Issue by mshark5** [veox/python3-krakenex#133]
Kraken updated their API and the add order endpoint on this wrapper doesn’t work anymore. Please fix it.

**Comment by veox** [comment]
> Kraken updated their API ...

What makes you say this? https://docs.kraken.com/rest/ still lists the same version.

> ... and the add order endpoint on this wrapper doesn’t work anymore. 

Yes it does, https://github.com/veox/python3-krakenex/blob/51f84694c732d4221eaa925a02ce519c63a83ae6/examples/order-conditional-close.py worked for me just fine.

> Please fix it.

File a proper bug report. The template is there for a reason.
