### ISSUE TITLE
why is fetching of balance returning error?

### ISSUE THREAD

**Issue by EmmanuelTom** [veox/python3-krakenex#135]
### Versions

```
OS:  Windows 11      
Python:    3.8
krakenex:  kraken
```

### What are you trying to achieve?
fetch balance

``` python
# code sample
#I'm using third party library known as ccxt
balance = exchange.fetch_balance()
print(balance)
```

### What do you expect to happen?
{'info': {'result': 'true', 'info': {'toBtc': {'egc': '0', 'iog': '0', 'ksm': '0', 'egg': '0', 'yfii3s': '0', 'gki': '0', 'fara': '0', 'sxp3s': '0', 'sxp3l': '0', 'idhub': '0', 'zrx3s': '0', 'yfii3l': '0', 'rad': '0', 'rabbit': '0', 'dot3l': '0', 'knc3s': '0', 'farm': '0', 'empire': '0', 'dot3s': '0', 'ten': '0', 'tep': '0', 'cdb': '0', 'cdc': '0', 'ata3s': '0', 'gmex': '0', 'ata3l': '0', 'ray': '0', 'stpl': '0', 'skl3l': '0', 'ankr3l': '0', 'lpt3l': '0', 'marsrise': '0', 'onot': '0', 'skl3s': '0', 'ankr3s': '0', 'tfd': '0', 'agld': '0', 'zrx3l': '0', 'lpt3s': '0', 'rbase': '0', 'eth3l': '0', 'klayg': '0', 'sero': '0', 'gmc': '0', 'eth3s': '0', 'aaa': '0', 'icx3l': '0', 'aac': '0', 'samo': '0', 'icx3s': 

### What happens instead?
{'info': {'error': []}, 'timestamp': None, 'datetime': None, 'free': {}, 'used': {}, 'total': {}}

``` python
# error message

```

**Comment by veox** [comment]
> #I'm using third party library known as ccxt

This issue tracker is for `krakenex`, not `ccxt`.

**Comment by veox** [comment]
BTW, looks like it's not returning an error: the `error` array is empty. I'm not familiar with that library to help any further, though.

I suggest finding the `ccxt` bug tracker and asking there. Or maybe this is expected behaviour.
