### ISSUE TITLE
post requests no longer accepted for market data endpoint

### ISSUE THREAD

**Issue by mallorymallory** [veox/python3-krakenex#139]
### Versions

```
OS:       rpi os (any)
Python:   3.7 (any)
krakenex: most recent
```

### What are you trying to achieve?

``` python3
import krakenex
k=krakenex.API()
k.query_public("Ticker", {"pair":"XBTUSD"})

```

### What do you expect to happen?
market data returned

### What happens instead?
405 client error - starting today apparently krakens no longer accepting post requests on market endpoints as per the docu 🙄 

``` python
requests.exceptions.HTTPError: 405 Client Error: Not Allowed for url: https://api.kraken.com/0/public/Ticker

```

**Comment by mallorymallory** [comment]
nvm i see ur already on this dog bless

**Comment by veox** [comment]
Heh, didn't even see the bug report. 

The change has come completely unannounced for me. :/

Should be working with version v2.2.1.
