### ISSUE TITLE
What are the asset pair names?

### ISSUE THREAD

**Issue by rjb25** [veox/python3-krakenex#16]
Do you have a list of the asset pair names you could post in the readme? 
Is there a link you could give me to find a list that already exists?
If you are wondering what I am looking for the `'pair'` parameter is what I am inquiring about. As in this example:
```
print(k.query_public('Depth',{'pair': 'XXBTZUSD', 'count': '10'}))
```
I know of the following but it just gives a huge blurb.
```
print(k.query_public('AssetPairs'))
```
For instance I want to know what Litecoin to Bitcoin pair name would be.

**Comment by rjb25** [comment]
I found my answer `XLTCXXBT` in parsing through the `AssetPairs`. However I think a comprehensive list would still help a lot with these seemingly random names.

**Comment by veox** [comment]
To get a prettier list, use [`pprint`](https://docs.python.org/3/library/pprint.html):

``` python
import pprint
pprint.pprint(k.query_public('AssetPairs'))
```

Or simply print the keys:

``` python
q = k.query_public('AssetPairs')
for k in q['result'].keys():
    print(k)
```

This may be added to the `examples`.

As to listing in the `README` - no. That's unnecessary manual labour.

**Comment by rjb25** [comment]
Ok, that code should work. Closing.
