### ISSUE TITLE
Don't use mutables as argument defaults in functions

### ISSUE THREAD

**Issue by kanu** [veox/python3-krakenex#19]
https://github.com/veox/python3-krakenex/blob/master/krakenex/api.py#L151
When defining functions like this `def query_private(self, method, req={}, conn = None):` you share a single instance of the `req` dictionary for every call that uses the default of `req`.

```python
def fn(x={}):
    return x

call1 = fn()
print(call1)
call1["a"] = "A"
call2 = fn()
print(call2)
print (call1 == call2)
```
If you want a fresh instance of an dictionary on every call of the function I suggest something like this.

```python
def fn(x=None):
    if x is None:
        x = {}
```

Nevertheless I don't see a concrete problem raised by this in your code.

**Comment by veox** [comment]
Looks like sugar. Good point, though.

Some of this code is slated to become obsolete - see #11. No warning for that has been issued yet, since there hasn't been a release.

Will try to include that when time permits. Feel free to PR, too.
