### ISSUE TITLE
'EAPI:Invalid nonce' when using python3-kraken concurrently (or around the same time) in different scripts

### ISSUE THREAD

**Issue by OmegaPhil** [veox/python3-krakenex#21]
I'm starting to use python3-krakenex with a few concurrent scripts, which results in the 'EAPI:Invalid nonce' error fairly frequently, even when I made more API keypairs and implemented a supposed random fetch of one pair per invocation (so making it very unlikely the same one would be picked at the same time, although this clearly doesn't work properly).

The documentation doesn't talk about this, is there any guidance on how to 'scale up' use of python3-krakenex, perhaps somehow share the nonce state? I haven't looked into the implementation yet. Kraken threatens to ban endpoints that create a lot of invalid nonces (which hasn't happened to me yet), so I'm sheepish to fiddle around with settings on Kraken - the settings are locked currently, but I remember something about a nonce window - but I'm betting fiddling with that would not suddenly allow multiple users of a keypair like I want?

**Comment by veox** [comment]
Sorry, but the issue description is too vague.

* OS, Python version, `krakenex` version?..
* Are these one-shot scripts, or contunuosly running clients?
* Are you opening a new connection on every query? If so, why?
* Why did you choose to pick one API key out of a pool, instead of assigning one per client?
* How many keys do you have in total? How do you guarantee that they're picked at random? How likely is it that the same one is picked?

-----

I'm not aware at all how Kraken load-balances queries when using multiple API keys.

With current stable `v0.1.4`, the nonce is set [here](https://github.com/veox/python3-krakenex/blob/v0.1.4/krakenex/api.py#L166) - slightly before the call is made.

**Comment by OmegaPhil** [comment]
This won't be anything todo with the OS or even python3-krakenex in particular, thats why I didn't go into any detail - just a case of 'something that happens when you run more than one script at once/close timewise with one API keypair', i.e. more of a Kraken thing + the nonce implementation.

For reference, Devuan Testing, Python 3.5.3, v0.0.6.2 (April 2016).

The particular scripts I'm using are one-shot commandline tools, some of which are then run in a loop with watch every 10 seconds - basically two panes in tmux - so yes, new connection on every query.

I only want 1 API keypair across all my scripts, however in order to not interfere with the other long-running polling scripts (that aren't supposed to be user interface tools) due to this nonce issue I made another 3 API keypairs dedicated to the commandline tools, and supposedly randomly fetch the keypair used after loading them into a dictionary (i.e. this is a dirty hack and not really important for the overall nonce issue):

```
keypair = random.choice(list(credentials.keys()))
```

The dictionary comes from a simple YAML doc:

```
key_1: {
    api_key: "super secret"
    private_key: "moar secret"
}
```

etc till key_3.

Atm I have ~5 user tools (not all used at once though) and 2-3 long running scripts, so I don't want to be creating keypairs for each.

Hmm, that looks really suspicious... that nonce should basically be unique and increasing in value no matter how many scripts I run at once (they're all on the same machine etc so no excuse for time skew). Initially I thought to hack in a central fetch of a shared number that always goes up, but theres no reason for the current nonce to be 'wrong'...

I can dump out the numbers the scripts are using later and then see if the nonce is somehow being sent 'out of order'.

**Comment by veox** [comment]
Haven't read your comment in full yet, but `v0.0.6.2`, but that had a bug with not releasing the file descriptor after reading in the key (see #7).

This has been fixed in [`v0.1.4`](https://github.com/veox/python3-krakenex/blob/master/CHANGELOG.rst#v014---2017-03-27-monday).

**Comment by OmegaPhil** [comment]
Yeah, its probably worth me upgrading and testing the scripts out regardless, but currently my scripts read the keys in and pass to krakenex:

```
api = krakenex.API(credentials['api_key'], credentials['private_key'])
```

**Comment by OmegaPhil** [comment]
Right, I've started syslogging the nonces used and when the error occurs, this is an excerpt of a few minutes of events when two scripts share a single keypair:

```
Jun 13 16:02:46 omega1 /kraken-overview.py: Nonce: 1497366166938
Jun 13 16:02:47 omega1 /kraken-overview.py: Nonce: 1497366167387
Jun 13 16:02:47 omega1 /kraken-overview.py: Nonce: 1497366167838
Jun 13 16:02:48 omega1 /kraken-position-list.py: Nonce: 1497366168277
Jun 13 16:02:48 omega1 /kraken-overview.py: Nonce failure detected!
Jun 13 16:02:48 omega1 /kraken-overview.py: Nonce: 1497366168955
Jun 13 16:02:49 omega1 /kraken-position-list.py: Nonce: 1497366169480
Jun 13 16:02:59 omega1 /kraken-overview.py: Nonce: 1497366179222
Jun 13 16:02:59 omega1 /kraken-position-list.py: Nonce: 1497366179945
Jun 13 16:03:00 omega1 /kraken-position-list.py: Nonce: 1497366180516
Jun 13 16:03:01 omega1 /kraken-overview.py: Nonce: 1497366181179
Jun 13 16:03:01 omega1 /kraken-overview.py: Nonce: 1497366181479
Jun 13 16:03:03 omega1 /kraken-overview.py: Nonce failure detected!
Jun 13 16:03:03 omega1 /kraken-overview.py: Nonce: 1497366183706
Jun 13 16:03:10 omega1 /kraken-position-list.py: Nonce: 1497366190934
Jun 13 16:03:12 omega1 /kraken-position-list.py: Nonce: 1497366192130
```

So basically there is no problem whatsoever with the nonce - it is always going up - presumably this means that someone inbetween me and Kraken is messing around with the order of the TCP packets, such that API queries close together aren't evaluated in order. Looks like I need to unlock the account and play with that window setting on a keypair...

I did manage to flush out a rogue watch command that was spamming kraken-position-list.py (you can see above 2 requests being made when that script only does one...), so at least that was a bonus.

**Comment by veox** [comment]
That's definitely not a normal use case. Every router between the machine and `api.kraken.com` is "messing" with those TCP packets - they're _two different connections_. Kraken probably terminates them both on the same API key handling endpoint/whatever. Or they should!..

What you need is to use a separate key for every connection, or write some "dispatcher".

That is out of `krakenex`'s scope.

**Comment by OmegaPhil** [comment]
Yes, but I would expect them to service the connections in roughly the same order they were initiated, but nvm - I think this is what the nonce window is for.

Yeah, if I get desperate I'll make an extra 'service' to provide a keypair when requested, which isn't the same as the last one.

**Comment by veox** [comment]
OK to close issue?

**Comment by OmegaPhil** [comment]
Yeah. For reference I'm testing a stupidly high nonce window now, equivalent to 15 seconds (15000), only now does it seem to be behaving itself on one key (so either Kraken is doing something very wrong or my traffic is under attack somehow).

**Comment by Endogen** [comment]
@OmegaPhil how did you fix that? I have the same issue and I don't have any possibility to identify the client since i use [python-telegram-bot](https://github.com/python-telegram-bot/python-telegram-bot) package to trade on kraken and there is no way to identify the client...

I feel it's kind of dirty to have more then one key and then just randomly change them. Any other ideas how to handle that?

**Comment by OmegaPhil** [comment]
I didn't - just using high nonce with multiple keys fed to krakenex.

**Comment by Endogen** [comment]
What about the idea to get a unique system value - something like this:

`from uuid import getnode as get_mac
mac = get_mac()`

and then save a few MAC addresses with there own key-pair and on every connection to the Kraken API check the MAC and set the corresponding keys? Any thoughts on that?

**Comment by Saxamos** [comment]
@OmegaPhil, can you explain how you set a higher nonce please? I got the same issue here but can't manage to do your trick :/

**Comment by Endogen** [comment]
More important then setting a higher nonce should be to use multiple keys. Create more then one key at Kraken and then in your bot set the first key, then call the Kraken API, then set the second key, then call the next Kraken API, then set the first key again, ...
So every time you call Kraken, you should change the key.
