### ISSUE TITLE
getaddrinfo failed

### ISSUE THREAD

**Issue by romainsuss** [veox/python3-krakenex#26]
Hi, 
When I run Depth.py I have this issue : 
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):

gaierror: [Errno 11004] getaddrinfo failed

I don't understand why....

**Comment by veox** [comment]
OS, Python version, `krakenex` version?..

**Comment by romainsuss** [comment]
Windows; Python 3.6; krakenex version '0.1.4' !

**Comment by veox** [comment]
Never tested using on Windows, so could be Windows-specific.

Please post the full stack trace.

-----

NB: Probably another reason to hand this off to `requests` (#11).

**Comment by romainsuss** [comment]
`import http.client
import urllib.request
import urllib.parse

  
class Connection:
    """Kraken.com connection handler.
  
    Public methods:
    close
    """
  
  
    def __init__(self, uri = 'api.kraken.com', timeout = 30):
        """ Create an object for reusable connections.
  
        Arguments:
        uri     -- URI to connect to (default: 'https://api.kraken.com')
        timeout -- blocking operations' timeout in seconds (default: 30)
        """
        self.headers = {
            'User-Agent': 'krakenex/0.0.3 (+https://github.com/veox/krakenex)'
        }
  
        self.conn = http.client.HTTPSConnection(uri, timeout = timeout)
        
        print('conn : ' , self.conn )
  
  
    def close(self):
        """ Close the connection.
  
        No arguments.
        """
        self.conn.close()
  
  
    def _request(self, url, req = {}, headers = {}):
        """ Send POST request to API server.
  
        url     -- Fully-qualified URL with all necessary urlencoded
                   information (string, no default)
        req     -- additional API request parameters (default: {})
        headers -- additional HTTPS headers, such as API-Key and API-Sign
                   (default: {})
        """
        data = urllib.parse.urlencode(req)
        print(data)
        headers.update(self.headers)
        self.conn.request("POST", url, data, headers)
        response = self.conn.getresponse()
  
        return response.read()
    
print(Connection()._request( 'https://api.kraken.com/0/public/Depth' , req = {}, headers = {}))`

**Comment by veox** [comment]
Please use three backticks for multi-line code inserts. (I've edited your post, and #28.)

What I asked for Was the error message, from `Traceback (most recent call last):` to (and including) the final error message.

The above looks like a part of the `connection` module's source code - and a very old one at that `v0.0.3`.
