### ISSUE TITLE
Connection persistence in _query function

### ISSUE THREAD

**Issue by AIEmpire** [veox/python3-krakenex#27]
Hi, forgive me if I'm getting this completely wrong, since I'm a novice programmer. 

Within the _query function, a check is performed to see if there is a connection object available. If there isn't a new one is created.

` if conn is None:
            if self.conn is None:
                conn = connection.Connection()
            else:
                conn = self.conn`

The comments in the code state 

> If not provided, opens a new connection for this and all
        subsequent queries.

However from looking at this code, it seems to me that the connection object would not be re-used for future queries, since it is being assigned to a local reference 'conn' which will be destroyed when the function exits. Therefore each time the function is called a new connection object is created?

Wouldn't the code be something like: 
` if conn is None:
            if self.conn is None:
                self.conn = connection.Connection()
            else:
                conn = self.conn`

**Comment by veox** [comment]
You might have just found the biggest bug so far. :)

**Comment by veox** [comment]
Blame points to commit af238233802bb2bad8bd669e5bb96372e252aa1e, from back when there was much less documentation, and when `_query()` wasn't really responsible for this.

**Comment by veox** [comment]
Fixed (I hope) to do in-code as it says in-docs.

Thanks for taking a look!

**Comment by AIEmpire** [comment]
No worries, glad I could help! 👍
