### ISSUE TITLE
`TradesHistory` example script not working out-of-the-box

### ISSUE THREAD

**Issue by BorstenElch** [veox/python3-krakenex#29]
Hi, 
I tried out this code as it is until line 45 as a test. Unfortunately my only output is:
{'error': [], 'result': {'trades': {}, 'count': 0}}
Same results when I am going to change the year to 2017 and the change in line 38 to:
end_date = datetime.datetime(2017, i+2, **28**)
Does anyone have a solution?
Thank you a lot in advance!
Best regards.

**Comment by veox** [comment]
> I tried out this code

What code?

**Comment by BorstenElch** [comment]
I meant the example code from krakenex for the method 'trades-history'.

**Comment by veox** [comment]
You mean this line: https://github.com/veox/python3-krakenex/blob/f6ad9c5fd6e4d67e693a407d114a38df8ea2a578/examples/trades-history.py#L45

The script requires the `pandas` Python package - do you have that installed?

The fact is not reflected in the script's header. Also, the comment there may be a stale copy-paste from `examples/form8949.py`.

The script was contributed by @AustinDeric in PR #13.

**Comment by zhuoyizhang** [comment]
Hi,

I tried this code and found that 2 rows were missing in the output.
In my Kraken account, there are 50 rows in July and August.  But in the csv, I only have 48 rows.

Below is the only changes I have made to your example.
```
for i in range(6,9):
    start_date = datetime.datetime(2017, i, 1)
    end_date = datetime.datetime(2017, i+1, 1) - datetime.timedelta(seconds=1)
    th = k.query_private('TradesHistory', req(start_date, end_date, 1))
```
Could you help?

**Comment by Rorchmain** [comment]
Hi there,
Thanks for the code. Unfortunately I do not manage to retrieve my trade history using it. I keep getting the following error : 
th = k.query_private('TradesHistory', data(start_date, end_date, 1))
TypeError: 'list' object is not callable
I am not sure que query_private('TradesHistory') expects as much inputs...
Thx for your help

**Comment by Rorchmain** [comment]
`th = k.query_private('TradesHistory', data(start_date, end_date, 1))
TypeError: 'list' object is not callable`

**Comment by Rorchmain** [comment]
Hi there,
Thanks for the code. Unfortunately I do not manage to retrieve my trade history using it. I keep getting the following error :
```
th = k.query_private('TradesHistory', data(start_date, end_date, 1))
TypeError: 'list' object is not callable
```
I am not sure que query_private('TradesHistory') expects as much inputs...
Thx for your help

**Comment by piotrjbedkowski** [comment]
@Rorchmain I encountered the same. Fixed https://github.com/veox/python3-krakenex/pull/81

**Comment by veox** [comment]
The script in question and the other one using `pandas` don't check for its version. Therefore, the backward-incompatible change in `pandas` API broke the scripts.

The above commit should do the same as in PR #81. Do reopen this issue if not so.

**Comment by christopheblp** [comment]
@Rorchmain have you resolved your issue ? I'm having the same problem...
