### ISSUE TITLE
Consider packaging on PyPI

### ISSUE THREAD

**Issue by zertrin** [veox/python3-krakenex#3]
Hi,

I'm the developer of [clikraken](https://github.com/zertrin/clikraken), and I depend on your library to interact with the Kraken API. However you don't provide a package on PyPI, which makes it harder to use it as a dependency in other projects such as mine.

Would you consider packaging it for PyPI? If not, I'm proposing to package it for you and upload it on PyPI myself. Just don't want to step on your toes in case you planned to do it sometime.

Thanks a lot for this library!

**Comment by veox** [comment]
It's been on my TODO list forever :D. [Submitted a source distribution](
https://pypi.python.org/pypi/krakenex/0.1.0).

**Comment by veox** [comment]
Is a built distribution also needed?

(JIC, this is my first (and only) PyPI package.)

**Comment by zertrin** [comment]
Well I'm not sure (clikraken is also my first and only PyPI package so far ^^). I will try to adapt and test my setup instructions for clikraken with your source package tomorrow, and report here.

Thanks a lot already for considering it!

**Comment by zertrin** [comment]
So yes that's working \o/ Just released clikraken 0.2.0 without steps for manual installation of dependencies.

Thanks a lot!

**Comment by zertrin** [comment]
Just to report that it works for me both on Linux and Windows. Couldn't get around testing on windows until today, but all works perfectly!
