### ISSUE TITLE
Consider adding a "cost averaging strategy" script as an example of long-term strategy automation

### ISSUE THREAD

**Issue by veox** [veox/python3-krakenex#30]
First mentioned in https://github.com/veox/python3-krakenex/issues/10#issuecomment-299805266, with reference to a [/r/CryptoCurrency discussion](https://www.reddit.com/r/CryptoCurrency/comments/5yyqn6/help_dollarcost_averaging_buying_eth_btc_on_a/) for context.

See PRs #14 and #15 for a (somewhat convoluted) example.

**Comment by veox** [comment]
See also [this gist](https://gist.github.com/pdaian/d634aed4fc040299513c2ac7294d7db4) for a Bittrex example.

**Comment by smechaab** [comment]
Is it still an open issue ?

**Comment by veox** [comment]
Not really. The "help wanted" tag is a placeholder. Guess it's OK to close...
