### ISSUE TITLE
Unable to retrieve private information

### ISSUE THREAD

**Issue by zlwolf236** [veox/python3-krakenex#31]
Hi All,

Hope you are doing great. I was able to use query_private to retrieve 'Balance', and 'Add Orders'.

And for some reason, it wouldn't work anymore. Although I make sure all my keys are right, the system return {'error': ['EAPI:Invalid key']}, or {'error': ['EGeneral:Temporary Lockout']} after like 3 attempts. It was working in the morning and it doesn't anymore. It will be very much appreciated if anyone could spare a hand.

Thank you

Best,
Wolf

**Comment by Adeleet** [comment]
Currently, I am experiencing this problem as well, and I think it has to do with the UTF8 encoding of the signature or private key. I am not getting the temporary lockout reponse by the way.

The weird part is that the 'public' API key is not working, while this should be the easiest part. The public key should not have any B64 encoding and should be sent as a raw header.
What Content-Type are you using for your request? (e.g. 'application/json' or 'application/x-www-form-urlencoded')

**Comment by Adeleet** [comment]
Here is the data that I am using (Pseudocode)

 - nonce (string), e.g. '1500119949325250'

- URI path (string), e.g. '/0/private/Balance'

- Post Data (string), without Two Factor Auth e.g. 'nonce=1500119949325250'

- SHA256(URI Path+Post Data), e.g. SHA256(1500119949325250nonce=1500119949325250)
= \xe9bS\x19t\xee`\xfe\x86\tO\x94AIN\x98\x90:{\xf9\xe5\xb8\xf9\x95\xce\xbc\xb7H\x85\x06[\x1c

- base64 decoded private key, e.g. base64 decode('myprivateapikey==') = \x9b*k\x8a\xf6\xady\xaab\x91\xec

-HMAC SHA512 of URI Path + SHA256(URI Path+Post Data) using the base64 decoded private key.

The two main culprits that I could see:

1 Not using either the the hex or byte version of the hashes. Right now I am using the hex versions, but using raw byte output will produce the same error:
Hex: \xa5\x91\xa6\xd4\x0b\xf4.....
Byte: a591a6d40bf420404a01.....

2 Not properly encoding before hashing (encode entire sha256 input as utf-8 or seperately)
A `hashlib.sha256(((str(nonce)+'nonce='+str(nonce)).encode('utf-8')))`
B `hashlib.sha256(str(nonce).encode('utf-8')+('nonce='+str(nonce)).encode('utf-8'))`

**Comment by Adeleet** [comment]
Here is the data that I am using (Pseudocode)

 - nonce (string), e.g. '1500119949325250'

- URI path (string), e.g. '/0/private/Balance'

- Post Data (string), without Two Factor Auth e.g. 'nonce=1500119949325250'

- SHA256(Nonce+Post Data), e.g. SHA256(1500119949325250nonce=1500119949325250)
= \xe9bS\x19t\xee`\xfe\x86\tO\x94AIN\x98\x90:{\xf9\xe5\xb8\xf9\x95\xce\xbc\xb7H\x85\x06[\x1c

- base64 decoded private key, e.g. base64 decode('myprivateapikey==') = \x9b*k\x8a\xf6\xady\xaab\x91\xec

-HMAC SHA512 (URI Path + SHA256(URI Path+Post Data)) using the base64 decoded private key.

The two main culprits that I could see:

1 Not using either the the hex or byte version of the hashes. Right now I am using the hex versions, but using raw byte output will produce the same error:
Hex: \xa5\x91\xa6\xd4\x0b\xf4.....
Byte: a591a6d40bf420404a01.....

2 Not properly encoding before hashing (encode entire sha256 input as utf-8 or seperately)
A `hashlib.sha256(((str(nonce)+'nonce='+str(nonce)).encode('utf-8')))`
B `hashlib.sha256(str(nonce).encode('utf-8')+('nonce='+str(nonce)).encode('utf-8'))`

**Comment by veox** [comment]
The `{'error': ['EGeneral:Temporary Lockout']}` is probably due to Kraken's request rate limiting.

Please provide OS/Python/krakenex versions.

**Comment by Adeleet** [comment]
I am using W10 build 15063.483, Python 3.6.2rc1 and I was using Krakenex v1.0.0a0. 

How to reproduce the issue:
I am using 'Advanced Rest Client' to test out the API. I edited the function `query_private()` function to return nothing but simply print out the nonce, the public key and the `sigidigest.decode()`.
So the `query_private()` contains this:

`self.secret = 'bH/56C2j.....'`
`self.key = 'YDW3gxelR....'`
` `
`---other code---`
` `
`print(req['nonce'])`
`print(self.key)`
`print(sigdigest.decode())`

Then I simply create an instance from the API class, run the query_private function and use these values in my REST Client:
`SPAM = API()`
`SPAM.query_private('Balance')`

**Comment by zlwolf236** [comment]
Thank you guys! I found my problem, thanks Adeleet for bringing it up. I forgot that I hardcoded hmac.py to encode secret for bitstamp, using the original hmac.py solve the problem.

Thank guys!
