### ISSUE TITLE
Exception Request-sent after 504

### ISSUE THREAD

**Issue by Neabfi** [veox/python3-krakenex#32]
Hello, I handle the exception when a 504 error occur.

But I cannot make any request after a 504 error.
I have a "Request-sent" exception ? Where did this come from ?

Thanks !

**Comment by veox** [comment]
Do provide OS/Python/`krakenex` versions.

Which exception?

Can you provide a code snippet or reference, together with the full traceback for this failure?

**Comment by Neabfi** [comment]
I have found the answer !

https://stackoverflow.com/questions/44933052/kraken-api-request-sent-exception
