### ISSUE TITLE
List of Commands

### ISSUE THREAD

**Issue by beeflowers287** [veox/python3-krakenex#33]
Could you print a list of available commands like below:

balance = k.query_private('Balance')
orders = k.query_private('OpenOrders')

specifically i'm looking for placing buys and sells

**Comment by veox** [comment]
No, at least not now.

The API methods are provided by Kraken, and listed in their [API docs](https://www.kraken.com/help/api), which is [linked from the README](https://github.com/veox/python3-krakenex#documentation).

Maintaining an up-to-date list is technical debt I'm not willing to accept at this point.

**Comment by veox** [comment]
For placing orders, see the [private user trading](https://www.kraken.com/help/api#private-user-trading) section.

**Comment by beeflowers287** [comment]
I got it.
