### ISSUE TITLE
Loop issues

### ISSUE THREAD

**Issue by beeflowers287** [veox/python3-krakenex#34]
I run this code in a loop to constantly scan for opportunities with my bot. 90% of the time after 5 min my code ends in an error like this:

  File "tradeKraken.py", line 34, in <module>
    balances = k.query_private('Balance')
  File "/usr/local/var/pyenv/versions/3.4.3/bin/krakenex/api.py", line 122, in query_private
    return self._query(urlpath, req, conn, headers)
  File "/usr/local/var/pyenv/versions/3.4.3/bin/krakenex/api.py", line 83, in _query
    return json.loads(ret)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

any ideas?

**Comment by beeflowers287** [comment]
Upon inspecting what's happening in api.py at that time I have printed ret and get that it times out at that point. 

<h2 data-translate="what_happened">What happened?</h2>
<p>The web server reported a gateway time-out error.</p>
</div>
<div class="cf-column">
<h2 data-translate="what_can_i_do">What can I do?</h2>
<p data-translate="try_again_in_a_few">Please try again in a few minutes.</p>

any idea on how to fix this so it can continue looping?

**Comment by beeflowers287** [comment]
I ended up using this
def is_json(myjson):
	  try:
		json_object = json.loads(myjson)
	  except ValueError, e:
		return False
	  return True

if is_json(ret):
        	return json.loads(ret)
        else:
        	time.sleep(30)
        	print "got here"
        return json.loads(ret)
but not sure how long to pause it. probable "a few minutes" like it says in the html?

**Comment by veox** [comment]
Kraken has had load issues for the last several months. There is nothing that can be done except for waiting on timeouts.

"A few minutes" should be reasonable.

Marking as "invalid", since not specific to `krakenex`.

-----

In the future, please format code blocks [with backticks](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#code). It is otherwise unreadable.

Also, do provide OS/Python/`krakenex` versions.
