### ISSUE TITLE
Adding the 'since: 0' parameter to the `query_public` function doesn't give any additional data

### ISSUE THREAD

**Issue by yenicelik** [veox/python3-krakenex#44]
### Versions

```
OS:  Mac OS 10.12.6 Sierra
Python:   3.6.2
krakenex: 0.1.4
```
### What are you trying to achieve?
I am trying to pull the entire historic data of all OHCL using the query_public keyword, to get all the trades from the beginning of time:

``` python
# code sample
tmp = self.apiKraken.query_public("OHLC", 
			{
			    "pair": "XETHXXBT",
			    "since": "100"
			})
```
### What do you expect to happen?
I expect to get the entire OHCL data from the beginning of time.

### What happens instead?
I get the same OHCL data as if I would not try to add the 'since' parameter. In short, the result is equivalent to 
```
tmp = self.apiKraken.query_public("OHLC", 
			{
			    "pair": "XETHXXBT",
			})
```
such that only a frame of the newest 700 samples is returned

``` python
# error message
I don't get an error message - This is a semantic error; From kraken's side, this should usually work.
```

**Comment by jacob-roth** [comment]
Does the `since` field take a timestamp string, a datetime object, a date string, or...?

**Comment by veox** [comment]
Kraken's API docs on `OHLC` [states](https://www.kraken.com/help/api#get-ohlc-data) that, for the request input data:

```
since = return committed OHLC data since given id (optional.  exclusive)
```

And in the result there's:

```
last = id to be used as since when polling for new, committed OHLC data
```

The documentation explicitly references the `since` value as an "id", not a "timestamp". Any interpretation as a timestamp would be user-implied.

**Comment by veox** [comment]
As to the original issue:

> I expect to get the entire OHCL data from the beginning of time.

Have you estimated the size of that response?.. With the default one-minute interval, and considering that the ETH/XBT pair was opened on 2015-08-08 (about two years ago), that'd be around 2*365*24*60 == 1051200 entries.

With an (optimistic) size of 100 bytes per entry, that's about 100.25 MiB.

**Comment by veox** [comment]
See [`examples/log-ohlc.py`](https://github.com/veox/python3-krakenex/blob/b66a413958a90057deb5d0aa2e0cb9ba2c24d95f/examples/log-ohlc.py#L15) for a (primitive, dirty) example of using `OHLC`.

**Comment by jacob-roth** [comment]
Based on a initial testing, the 'since' with 'timestamp' has worked for me. What I've found weird is that the timestamp must be in local timezone, and the 'time'
field returned by Kraken is local too...

**Comment by yenicelik** [comment]
Thanks guys, that was a great help! I did not understand that it has to be a local timezone in the Unix timestamp. Also, thx @veox for the example! :)
