### ISSUE TITLE
Support Conda installation 

### ISSUE THREAD

**Issue by kscheung1228** [veox/python3-krakenex#47]
### Versions

```
OS:       
Python:   
krakenex: 0.1.4
```

### What are you trying to achieve?

Try to perform basic balance checking in the examples
https://github.com/veox/python3-krakenex/blob/master/examples/print-account-balance.py

``` python
# code sample

import krakenex

k = krakenex.API()

# next raw comment line added by veox
```

### What do you expect to happen?
I expect it to show the balance 

### What happens instead?

It doesnt run , i believe this is because of the version installed doesnt have the API yet ? 

``` python
# error message
Traceback (most recent call last):
  File "krakenex.py", line 1, in <module>
    import krakenex
  File "/Users/kashingcheung/Desktop/Coursera/AnacondaProjects/Kraken/krakenex.py", line 3, in <module>
    k = krakenex.API()
AttributeError: module 'krakenex' has no attribute 'API'

```

**Comment by veox** [comment]
Version 0.1.4 does have `API` exported.

0.1.4 is the current stable. `API` has been there since version 0.0.1 (i.e. always).

As per the issue title... Do you mean [the distribution](https://en.wikipedia.org/wiki/Anaconda_(Python_distribution)) and [it's package manager](https://en.wikipedia.org/wiki/Conda_(package_manager))?..

**Comment by kscheung1228** [comment]
I thought it is version issues thats why I point it to the distribution and its package manager?
In that case , my issues is pretty srtaight forward - I use the [example](https://github.com/veox/python3-krakenex/blob/master/examples/print-account-balance.py)

However, it comes back with below error

# error message
Traceback (most recent call last):
  File "krakenex.py", line 1, in <module>
    import krakenex
  File "/Users/kashingcheung/Desktop/Coursera/AnacondaProjects/Kraken/krakenex.py", line 3, in <module>
    k = krakenex.API()
AttributeError: module 'krakenex' has no attribute 'API'

**Comment by veox** [comment]
So... You've created a file called `krakenex.py`, to which you've copied the contents of `examples/print-account-balance.py`. Correct?

If so, you're shadowing the actual `krakenex` module.

**Comment by veox** [comment]
That is, don't name your script same as the package.

**Comment by veox** [comment]
Did the above advice help resolve the issue?

**Comment by kscheung1228** [comment]
Yes.  Thanks !
