### ISSUE TITLE
Permission denied for all private requests with 2FA

### ISSUE THREAD

**Issue by ash09** [veox/python3-krakenex#50]
### Versions

```
OS:       Archlinux
Python:   3.6.2
krakenex: installed using pip
```

Hi all,
I'm not able to get my balance on Kraken. I think the problem is related to the 2FA. Here's how I do it.

``` python
kraken = krakenex.API(apiKey,apiPassword)
totp = pyotp.TOTP(password2FA)
r = kraken.query_private("TradeBalance",{"otp": totp.now()})
```
I get the following: 'EGeneral:Permission denied'.

Any help would be greatly appreciated.

**Comment by ash09** [comment]
Problem solved.

**Comment by veox** [comment]
My use cases have all been of the "unsupervised monitoring" flavor, where 2FA isn't very useful.

Could you give a short description of how you fixed this, in case someone else has the same problem?
