### ISSUE TITLE
Resetting krakenex connection

### ISSUE THREAD

**Issue by PilotMan87** [veox/python3-krakenex#53]
### Versions

```
OS: Windows
Python: 3.6.2
krakenex: v1.0.0c1
```

### What are you trying to achieve?
Close an open connection after timeout

``` python
# code sample
def query_order(k, txid):

		options = {'txid':''}
		options['txid'] = txid
		
		try:
			print ("querying open orders")
			values = k.query_private('QueryOrders',options)
			print ("result")
			print (values)
			return values
		except:
			print ("query_pair: Unexpected error:", sys.exc_info()[0])
			# probably a timeout, sleep 60 seconds and try again
			k.conn = None
			time.sleep(60)		
		
		return None
```

### What do you expect to happen?
I would like to close/reset the krakenex connection. Since I am running a lot in some sort of endless loop of timeouts, which, miraculously always get resorted after I restart my code.
Now I thought the k.conn = None would sort that issue.
It does, kind of, it creates a new connection and the timeout issue disappears.
However if the bot runs long enough, which now happened after 16h, the shell had so many instances that I was getting socket errors until I closed the entire shell and started in a fresh shell.
My best attempt was k.conn.close() but the below code returns:
``` python
# code sample
k.query_public('Ticker',dict([('pair', 'XXBTZEUR')]))
print (k.conn)
k.conn.close()
print (k.conn)
k.query_public('Ticker',dict([('pair', 'XXBTZEUR')]))
print (k.conn)
```
``` python
# message
<krakenex.connection.Connection object at 0x036607B0>
<krakenex.connection.Connection object at 0x036607B0>
<krakenex.connection.Connection object at 0x036607B0>
```
I don't know, is it really creating a new connection at the next query? if I use my shitty k.conn = None method I get a new memory imprint.

No idea how to handle those infinite timeouts, or well, reset krakenex connection without creating a dead instance.

**Comment by veox** [comment]
Connection handling in `krakenex` is confusing indeed - sorry about that!

It's been implemented in the most straightforward manner in times when Kraken didn't really have load issues.

I'll try to provide a breakdown below.

-----

`k.conn.close()` does just that - it [closes the connection](https://github.com/veox/python3-krakenex/blob/v1.0.0c1/krakenex/connection.py#L53), which [is a `http.client.HTTPSConnection` object](https://github.com/veox/python3-krakenex/blob/v1.0.0c1/krakenex/connection.py#L50). This does not replace the `Connection` (`k.conn`) that is an attribute of `krakenex.API` (`k`).

A subsequent `k.query_public()` also does not check the state of the connection, so the query "falls through" to the same connection that was closed. I haven't looked into what happens then, but I'd guess it's nothing good.

-----

Doing `k.conn = None` leaves the previous `Connection` "open". That likely means it's not picked up by the garbage collector.

Now, if `k.conn` is `None`, `krakenex.API` [picks up on the fact](https://github.com/veox/python3-krakenex/blob/v1.0.0c1/krakenex/api.py#L139), and creates a new `krakenex.Connection`, which will be used for subsequent queries - until this one, too, flakes out.

-----

To "work around" this, it would seem that you have to do:

``` python
k.conn.close() # won't be talking through this anymore
k.conn = None # remove object reference - allow picking up by GC
time.sleep(60) # magicnum 60: arbitrary long interval
k.conn = krakenex.Connection() # optional, open new connection _now_
```

This should probably be added as `API.close()` or something...

-----

It seems that if people were "resetting" the connection like you do here, it likely was a contributing factor to Kraken instability, seeing how large numbers of connections were allowed to "linger".

**Comment by veox** [comment]
If the above guess is correct, I wonder why Kraken's sysadmins didn't come here screaming to fix this crap.

This should probably get fixed before `v1.0.0` release, although that does mean introducing new functionality in a haphazard manner.

In the long run, this should be replaced by `requests`, as outlined in #11.

**Comment by veox** [comment]
OTOH, it'll perhaps easier to push `v1.0.0` out the airlock, and then scramble for `v2.0.0`...

**Comment by veox** [comment]
I've modified the (deprecated!) `API.set_connection()` to close the existing connection before creating a new one.

A one-liner should be possible to use in `v1.0.0`, although it's a mouthful:

``` python
k.set_connection(krakenex.Connection())
```

I'm not recommending using it, though, since it'll be removed anyway.

**Comment by PilotMan87** [comment]
You rock! Thanks heaps.
Bot is running since hours.
I loved my garbage collection of lost orders, had a - vs + error and it sold everything at the worst possible moment. I love live programming. It's like being in a casino :DDDD dat thrill
