### ISSUE TITLE
OHLC intervals

### ISSUE THREAD

**Issue by Newb0987** [veox/python3-krakenex#55]
Hi,

How do I change the default interval of OHLC from 1 to 60?

thanks,

**Comment by veox** [comment]
Did you take a look at the [docs](https://www.kraken.com/help/api#get-ohlc-data)?

**Comment by Newb0987** [comment]
Yes I did.

I have tried modifying the _query function by changing:

self.response = self.session.post(url, data = data, headers = headers, interval=60)

but this seems to fail. Sorry I am not a seasoned developer.

thanks for any help.

**Comment by veox** [comment]
Take a look at [`examples/log-ohlc.py](https://github.com/veox/python3-krakenex/blob/a4ee0f3d70146734b507a6037aa4d96dd93e0415/examples/log-ohlc.py#L40).

With `krakenex` v2.0.0a1, your query should look something like:

``` python
response = k.query_public('OHLC', data = {'pair': pair, 'interval': 60})
```

**Comment by Newb0987** [comment]
Hi,

Yes, I have just figured it out myself. Many thanks for your help!
