### ISSUE TITLE
pip3 for python3?

### ISSUE THREAD

**Issue by georoen** [veox/python3-krakenex#57]
Hi, I'm new to python and struggled following the [installations](https://github.com/veox/python3-krakenex/blob/master/README.rst#installation). I figured out though, that using `pip3 install krakenex` instead of `pip ...` worked out. Is this normal? Has the readme to be edited?
Thanks :-)

**Comment by veox** [comment]
The `pip` binary's name is distribution-dependent. On Debian-based ones, it's `pip3`.

**Comment by georoen** [comment]
Thanks! I'll herewith close this issue. :-)
