### ISSUE TITLE
api return "Request-sent" after a "read operation timed out"

### ISSUE THREAD

**Issue by yepla** [veox/python3-krakenex#59]
Hello,
When i cancel an order then there are a read operation timed out api not return result or error but the message "Request-sent" when i try to cancel again the order :(
Does it s normal ?
How can i know my order has been cancelled or if it s in pending ?
I m using python3 and the pip version of krakenex.
Thanks for your answer.

**Comment by yepla** [comment]
same for AddOrder when a timeout appear api return Request-sent and not the txids :(
a little bit problematic !

**Comment by yepla** [comment]
I m using actually the krakenex 1.0.0
I will try to use the last one !
keep in touch

**Comment by veox** [comment]
Seeing your question, I've decided to pack up a release candidate with the latest changes. `requests`'s network error handling is superior to what's in `v1.0.0`.

**Comment by yepla** [comment]
i have install the v2.0.0a1 does it s the current stable version ?

**Comment by veox** [comment]
Yes. I've _just_ pushed `v2.0.0c1`, which is also on PyPI, but there are no code changes from `v2.0.0a1`.

**Comment by veox** [comment]
As to the issue at hand, I've never encountered a "Request-sent" message.

**Comment by yepla** [comment]
with the last version i don't have this issue
