### ISSUE TITLE
Using krakenex with a proxy/ behind a proxy

### ISSUE THREAD

**Issue by wwender** [veox/python3-krakenex#6]
Currently krakenex will not work with a proxy/behind a proxy without code change cause it's https requests are based on http.client and urllib.

Best would be to have it based on requests. There the system/OS proxy settings are automatically used. 

What I did for krakenex was to change the connection.py. With a proxy at : myserver:1111 it has to be changed from 
self.conn = http.client.HTTPSConnection(uri, timeout = timeout)

to 

self.conn = http.client.HTTPSConnection("myserver:1111", timeout = timeout)
self.conn.set_tunnel(uri)

**Comment by veox** [comment]
Didn't dwell too much yet, but this does seem to be a more valid reason than #2.

**Comment by veox** [comment]
PR #36 implements this on current `master`.

**Comment by ScriptProdigy** [comment]
@veox if I may ask, why the choice for urllib and http.client over requests? To stay more to standard python libs? Or is there another technical reason you saw? Maybe just personal preference, I personally would have used requests out of preference, though not a problem. Saw this issue browsing and thought it interesting is all.

**Comment by veox** [comment]
"No dependencies" was the main reason, yes.

**Comment by ScriptProdigy** [comment]
Thanks for the quick reply, fair enough :) Thanks for creating this lib, works swell :D

**Comment by veox** [comment]
`requests-updated` has been merged to `master`. Also released `v2.0.0a1` (alpha).
