### ISSUE TITLE
How to Connect ? username, password...

### ISSUE THREAD

**Issue by AlexandreGazagnes** [veox/python3-krakenex#62]
Hello Everyone, 

Sorry to ask that, but i have a major Noob question : from a python script, using krakenex, How could you connect to your personal account? 

OK there is k.load_key() but nowhere we have to input username, password etc etc.

I think this is a very dumb question but sorry, I've been searching for 1 hour and nothing...

Thanks a lot

Alex

```
OS:       Ubuntu 16.04 lrs
Python:   3.5
krakenex:  - 
```

### What are you trying to achieve?

``` python
# code sample

```

### What happens instead?

``` python
# error message

```

**Comment by veox** [comment]
When you log into Kraken (with username, password, and 2FA ;)), go to Settings -> API and generate a new key/secret pair.

**Comment by AlexandreGazagnes** [comment]
Thanks a lot i will try it ASAP.
For the nonce, an advice? 

thks

Alex

**Comment by veox** [comment]
> For the nonce, an advice?

The nonce is handled, derived from local time, at millisecond precision.

You can [override `krakenex.API._nonce()`](https://github.com/veox/python3-krakenex/blob/v2.0.0c2/krakenex/api.py#L171) if needed.
