### ISSUE TITLE
Permission denied for all private requests

### ISSUE THREAD

**Issue by vutrongvu** [veox/python3-krakenex#63]
### Versions

```
OS:  Ubuntu 14.0
Python:   3.5
krakenex: latest
```

Hi all,
I'm not able to get my balance on Kraken. Here's how I do it.

        self.api_key = 'XXXX'
        self.api_secret = 'XXXXXX'
        conn = krakenex.Connection()
        self.api = krakenex.API(API_KEY, API_SECRET)
        orders = self.api.query_private('Balance')

I get the following: 'EGeneral:Permission denied'.

Any help would be greatly appreciated.

**Comment by veox** [comment]
You are definitely not using the latest version of `krakenex`. The `Connection` class has been removed.

Also, you're setting `self.api_{key,secret}` atrributes, and then not using them.

**Comment by vutrongvu** [comment]
OK thanks.
