### ISSUE TITLE
How to set timeout?

### ISSUE THREAD

**Issue by Endogen** [veox/python3-krakenex#67]
### Versions

```
OS: macOS 10.13.1
Python: 3.6.3
krakenex: 2.0.0c2
```

### What are you trying to achieve?
Get a response from Kraken

``` python
kraken = krakenex.API()
kraken.load_key("kraken.key")

res_add_order = kraken.query_private("AddOrder", req_data)
```

### What do you expect to happen?
Request should wait till response is returned

### What happens instead?
I get no response

**Comment by veox** [comment]
OT: How long have you tried to wait?..

For me, _all_ queries return a response (or raise a `requests` exception) within 1 minute. Most queries that would interact with Kraken's trade execution engine are "resolved" within 10-20 seconds, but quite often go up to 30.

**Comment by Endogen** [comment]
Sorry, my bad. I get an `requests` error. I just didn't catch it.
```
requests.exceptions.HTTPError: 502 Server Error: Bad Gateway for url: https://api.kraken.com/0/private/AddOrder
```

Is it just me or isn't it possible right now to create an order at Kraken via API? Sorry for the mess, i do realize that this has nothing todo with my initial question...

**Comment by veox** [comment]
No problem!

ATM, Kraken is indeed a mess; `502`s were fairly common in recent months, but there's ample `504`s and `520`s now.

**Comment by veox** [comment]
BTW, careful with `502`s: [PSA on /r/krakenex](https://www.reddit.com/r/krakenex/comments/778uvh/psa_http_error_502_does_not_mean_the_query_wont/).

**Comment by veox** [comment]
Please don't close the issue, though: the topic question is still valid.

**Comment by TheSeven** [comment]
Tonight I had a situation where quite likely my internet connection was dropped while krakenex was waiting for a reply. That ended up waiting for that reply endlessly (hours), so adding a (reasonable) timeout would still be a good idea, even if this only occurs rarely.

**Comment by moppymopperson** [comment]
I sometimes have the same problem as @TheSeven. I run a script that queries the public endpoint for the current price at regular intervals, and occasionally I’ll get a response that never comes back. Currently I have to manually inspect and reset, but I’d really like to handle it with a timeout to just give up and move on.

**Comment by veox** [comment]
PR #77 has been merged - introducing a `timeout` arg to the `query_{public,private}` functions.

The value passed should be a number (`int` or `float`).

For now, there is no way to set a default timeout (for all queries and/or connection opening).
