### ISSUE TITLE
Doesnt run after install

### ISSUE THREAD

**Issue by JLHelm** [veox/python3-krakenex#72]
running on ubuntu linux
>>pip install clikraken

>> clikraken --version
Traceback (most recent call last):
  File "/home/sard/.local/bin/clikraken", line 7, in <module>
    from clikraken.clikraken import main
  File "/home/sard/.local/lib/python2.7/site-packages/clikraken/__init__.py", line 1, in <module>
    from clikraken.__about__ import (
  File "/home/sard/.local/lib/python2.7/site-packages/clikraken/clikraken.py", line 12, in <module>
    from clikraken.api.api_utils import load_api_keyfile
ImportError: No module named api.api_utils

**Comment by JLHelm** [comment]
solved by installing with pip3 *and* changing /home/sard/.local/bin/clikraken

#!/usr/bin/python
=>
#!/usr/bin/python3

**Comment by veox** [comment]
You probably meant to report this in https://github.com/zertrin/clikraken. ;)

**Comment by veox** [comment]
Both `krakenex` and `clikraken` assume Python 3 is the default, which is still not the case on many Debian derivatives.

**Comment by JLHelm** [comment]
Sorry! Bit of a train-wreck of an issue, really. Thanks for responding anyway.

**Comment by JLHelm** [comment]
Out of interest, is there a way for devs like yourself to make this issue less opaque or avoid it entirely? I feel like pip shouldn't be able to install a package if it won't work. I get that users just have to switch to python 3, but how come pip happily installed a python3 packed on a python 2.7 base and didn't even throw a warning?

**Comment by veox** [comment]
Honestly, I haven't looked into this yet - until now!

Looks like [there is a way](https://packaging.python.org/tutorials/distributing-packages/#python-requires) that `krakenex` is currently lacking.

**Comment by veox** [comment]
What's `pip`'s version on Ubuntu?.. I've just added this bit to `setup.py`, but the linked docs say:

> In addition, only versions 9.0.0 and higher of pip recognize the `python_requires` metadata.

**Comment by JLHelm** [comment]
$ pip -V
pip 9.0.1 from /usr/local/lib/python3.5/dist-packages (python 3.5)
$ uname -a
Linux glass 4.10.0-42-generic #46-Ubuntu SMP Mon Dec 4 14:38:01 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 17.04
Release:	17.04
Codename:	zesty

So for >17.04 you should be good?
That looks like a good fix, well found :)

**Comment by JLHelm** [comment]
I'm now wondering which part of my solution was the fix - the shebang or the pip3 install. Or both. I don't know enough about how the python 2/3 issue behaves with module installation.

**Comment by veox** [comment]
If `virtualenv` is not used, then I'd guess both the shebang (specifically for `clikraken` script) and the `pip3` install (for dependencies) are needed.
