### ISSUE TITLE
Cannot send market order

### ISSUE THREAD

**Issue by Jambon1510** [veox/python3-krakenex#73]
### Versions

```
OS: Ubuntu 16.04.1
Python: Python 3.5.2
krakenex: 2.0.0

```

### What are you trying to achieve?
I am trying to send a market order

``` python
import krakenex

k = krakenex.API()
k.load_key('kraken.key')

def send():
        try:
                k.query_private('AddOrder',
                        {'pair': 'XXRPZEUR',
                         'type': 'buy',
                         'ordertype': 'market',
                         'volume': '1'
                        })
        except:
                print("failed, retrying...")
                send()

send()

```

### What do you expect to happen?
I am expecting to see a position the order executed from the website or via the API (no trades history either with the above order instructiob)

### What happens instead?
No order shown on either website nor API (no output)

**Comment by veox** [comment]
No output does seem very strange - not even the "failed, retrying..."?

-----

Other than that, this approach to re-sending is both spammy (no delay between retries) and dangerous (to your funds).

To understand why, read [this PSA](https://www.reddit.com/r/krakenex/comments/778uvh/psa_http_error_502_does_not_mean_the_query_wont/) and issue #66. (Those also have code snippets for safer order placing linked throughout.)

**Comment by Jambon1510** [comment]
Yes no output because everything seems to be ok in the try.
As it is a test I have to admit I was lazy setting up a sleep, my main program does have it in the except for others API call.

Le me rephrase and send another piece of code, it will be clearer this time hopefully.
When executing the below I have the output "order sent" but nothing is actually sent when checking on website or via the API

```python
import krakenex

k = krakenex.API()
k.load_key('kraken.key')

def send():
            k.query_private('AddOrder',
                    {'pair': 'XXRPZEUR',
                     'type': 'buy',
                     'ordertype': 'market',
                     'volume': '1'
                    })
            print("order sent")

send()

```

**Comment by veox** [comment]
Ah! Unless you're running this in an interactive session, There won't be any.

Try:

``` python
response = k.query_private(...)
print(response)
```

**Comment by Jambon1510** [comment]
it was obvious, thanks for your help

It ended up to be a minimum volume issue after having the output setup properly: 
{'error': ['EGeneral:Invalid arguments:volume']}
https://support.kraken.com/hc/en-us/articles/205893708-What-is-the-minimum-order-size-
