### ISSUE TITLE
Problem with SSL on Mac OS X (Yosemite)

### ISSUE THREAD

**Issue by adreu** [veox/python3-krakenex#8]
Hi,

I m trying to use the API but I got this issue when I call query public 
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749)

Can you help me ?

Thanks

**Comment by veox** [comment]
Since it's `query_public()`, could you provide a code example that fails for you?

**Comment by veox** [comment]
Also, which OS are you using, which Python version, and which version of `krakenex`?

**Comment by adreu** [comment]
I just tried to use the python source example file 
I changed the Key File but using my credentials

OS = Mac OS X (Yosemite)
Python 3.6.0
__version__ = '0.1.3'
__url__ = 'https://github.com/veox/python3-krakenex'


```
import krakenex

k = krakenex.API()
k.load_key('kraken.key')

k.query_public('Assets')
```

**Comment by veox** [comment]
Public API methods don't require a key, and for me both of the following work (using same Python 3.6.0 and `krakenex` 0.1.3 installed via `pip`):

``` python
import krakenex

krakenex.API().query_public('Assets')

k = krakenex.API()
k.load_key('kraken-test.key')
k.query_public('Assets')
```

Only thing I can think of is OS X not liking the cert provided by api.kraken.com. It's issued by Comodo for `<some-server>.cloudflaressl.com`.

Can you verify that the root CA certs installed on your machine are up-to-date? If they are, could you post the full trace generated by:

``` python
import krakenex
krakenex.API().query_public('Assets')
```

**Comment by veox** [comment]
In particular, does going to https://api.kraken.com/ in a browser give any warnings?

**Comment by adreu** [comment]
On keychain access > system / certificates I got this :
![image](https://cloud.githubusercontent.com/assets/9079264/23615320/503809ac-0286-11e7-9e19-d697af27bf1f.png)

I modified conditional-close.py with your last code 

`Traceback (most recent call last):
  File "conditional-close.py", line 2, in <module>
    krakenex.API().query_public('Assets')
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/krakenex/api.py", line 113, in query_public
    return self._query(urlpath, req, conn)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/krakenex/api.py", line 97, in _query
    ret = conn._request(url, req, headers)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/krakenex/connection.py", line 71, in _request
    self.conn.request("POST", url, data, headers)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 964, in send
    self.connect()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1400, in connect
    server_hostname=server_hostname)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ssl.py", line 401, in wrap_socket
    _context=self, _session=session)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ssl.py", line 808, in __init__
    self.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ssl.py", line 1061, in do_handshake
    self._sslobj.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ssl.py", line 683, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749)`

With Chrome when I connect to https://api.kraken.com/ I got this 
{"error":["EGeneral:Unknown method"]}

But if I connect to https://api.kraken.com/0/public/Assets
I got 

> {"error":[],"result":{"KFEE":{"aclass":"currency","altname":"FEE","decimals":2,"display_decimals":2},"XDAO":{"aclass":"currency","altname":"DAO","decimals":10,"display_decimals":3},"XETC":{"aclass":"currency","altname":"ETC","decimals":10,"display_decimals":5},"XETH":{"aclass":"currency","altname":"ETH","decimals":10,"display_decimals":5},"XICN":{"aclass":"currency","altname":"ICN","decimals":10,"display_decimals":5},"XLTC":{"aclass":"currency","altname":"LTC","decimals":10,"display_decimals":5},"XNMC":{"aclass":"currency","altname":"NMC","decimals":10,"display_decimals":5},"XREP":{"aclass":"currency","altname":"REP","decimals":10,"display_decimals":5},"XXBT":{"aclass":"currency","altname":"XBT","decimals":10,"display_decimals":5},"XXDG":{"aclass":"currency","altname":"XDG","decimals":8,"display_decimals":2},"XXLM":{"aclass":"currency","altname":"XLM","decimals":8,"display_decimals":5},"XXMR":{"aclass":"currency","altname":"XMR","decimals":10,"display_decimals":5},"XXRP":{"aclass":"currency","altname":"XRP","decimals":8,"display_decimals":5},"XXVN":{"aclass":"currency","altname":"XVN","decimals":4,"display_decimals":2},"XZEC":{"aclass":"currency","altname":"ZEC","decimals":10,"display_decimals":5},"ZCAD":{"aclass":"currency","altname":"CAD","decimals":4,"display_decimals":2},"ZEUR":{"aclass":"currency","altname":"EUR","decimals":4,"display_decimals":2},"ZGBP":{"aclass":"currency","altname":"GBP","decimals":4,"display_decimals":2},"ZJPY":{"aclass":"currency","altname":"JPY","decimals":2,"display_decimals":0},"ZKRW":{"aclass":"currency","altname":"KRW","decimals":2,"display_decimals":0},"ZUSD":{"aclass":"currency","altname":"USD","decimals":4,"display_decimals":2}}}

**Comment by veox** [comment]
Looks like Python-centric then. Does accessing HTTPS-enabled websites with Python work for you in general?

How was Python installed? In particular, does [this](https://stackoverflow.com/questions/42098126/mac-osx-python-ssl-sslerror-ssl-certificate-verify-failed-certificate-verify) apply?

**Comment by adreu** [comment]
Yes ! It fix it.. Thanks a lot ! 
Have a good day and thanks again
