### ISSUE TITLE
Get all orders history

### ISSUE THREAD

**Issue by 2803media** [veox/python3-krakenex#82]
### Versions

```
OS:       
Python:  3 
krakenex: last one
```
Hi

I just notice that the following query didn't get all the orders for the selected start timestamp

```
response = kraken.query_private('ClosedOrders',{'trades': 'true','start':'1514790000'})

```

Is there a limit for this kind of query (date or number of results)?

Thanks

**Comment by veox** [comment]
Do see [Kraken's docs](https://www.kraken.com/help/api#get-closed-orders) on this. Use `ofs` in query.
