### ISSUE TITLE
'EGeneral:Invalid arguments:ordertype' error with some order types

### ISSUE THREAD

**Issue by SB0gmail** [veox/python3-krakenex#86]
### Versions

```
OS:  Windows 10
Python:   3
krakenex: 
```
I am able to achieve market and limit orders with code:
myorder = k.add_standard_order(pair = tradepair,type = 'sell',ordertype = 'market',volume = buylots, price = myprice)

But when I try to put a stop loss or trailing stop order with equivalent code:
myorder = k.add_standard_order(pair = tradepair,type = 'sell',ordertype = 'trailing-stop',volume = buylots, price = myprice)

I get an error "KrakenAPIError: ['EGeneral:Invalid arguments:ordertype']"
Please help.

**Comment by veox** [comment]
`krakenex` has no `add_standard_order()`.

You are likely using some other library - the only one I know of is https://github.com/dominiktraxl/pykrakenapi.

If you are, report the issue there.

**Comment by SB0gmail** [comment]
thanks, that is what I wanted to do. Dunno how I ended up pasting here.
