### ISSUE TITLE
PIP Install is not latest version

### ISSUE THREAD

**Issue by pmorange** [veox/python3-krakenex#90]
### Versions

```
OS:       Ubuntu
Python:   3.5.2
krakenex: 2.0.0
```

### What are you trying to achieve?
Install latest krakenex version

``` python
# code sample
sudo pip3 install krakenex
```

### What do you expect to happen?
Have the latest version installed

### What happens instead?
I have version 2.0.0 installed, but when I look closer, it is not the latest as in Git.
I discovered that because I wanted a timeout on the requests to Kraken. Was about to open a new issue and saw that the changes had already been commited in Git. 
If I compare the Git api.py file with the file that is install with pip3, I see that I am missing the "timeout=None" parameter in the methods...

``` python
# error message

```

**Comment by veox** [comment]
`pip` installs stable packages. I haven't had time to make a package with the latest changes in `git`.

**Comment by veox** [comment]
Going through the motions now. Package should be available within an hour.

**Comment by veox** [comment]
Package should be available now. I've skipped the extensive local testing I usually do.

If there's issues with `v2.1.0`, please open new ones.

**Comment by pmorange** [comment]
Thanks a lot !!!
